<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INsaikrisv.local" name="Command line test" tests="4" failures="2" timestamp="10 Jan 2016 07:40:23 GMT" time="0.037" errors="0">
  <testcase name="testApp on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.test.sample.SampleTest.testApp(SampleTest.java:14)
	at com.test.sample.Runner.testRunnerTestNg(Runner.java:77)
	at com.test.sample.Runner$1.runTests(Runner.java:58)
	at com.test.sample.Runner$1.run(Runner.java:52)
	at java.lang.Thread.run(Thread.java:745)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testApp on [SampleTest passed=0 failed=0 skipped=0] -->
  <testcase name="testApp1 on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest"/>
  <testcase name="testApp2 on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.test.sample.SampleTest.testApp2(SampleTest.java:28)
	at com.test.sample.Runner.testRunnerTestNg(Runner.java:77)
	at com.test.sample.Runner$1.runTests(Runner.java:58)
	at com.test.sample.Runner$1.run(Runner.java:52)
	at java.lang.Thread.run(Thread.java:745)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testApp2 on [SampleTest passed=0 failed=0 skipped=0] -->
  <testcase name="testApp3 on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest"/>
</testsuite> <!-- Command line test -->
